@endpoint = http://localhost:3000/api/v1/cars

###
# @name postACar


POST {{endpoint}} HTTP/1.1
content-type: application/json

{
    "make": "make2",
    "model": "model2"
}


###

@newCar = {{postACar.response.body._id}}
###
GET  {{endpoint}}/{{newCar}} HTTP/3.0
content-type: application/json

###
GET  {{endpoint}}/sillycarID HTTP/3.0

content-type: application/json


###

DELETE  {{endpoint}}/sillycarID HTTP/3.0
content-type: application/json

###

PUT  {{endpoint}}/sillycarID HTTP/3.0
content-type: application/json
